kind: pipeline
type: docker
name: sonar_analysis

steps:
  - name: list_files
    image: maven:3.6.3-jdk-11
    commands:
      - ls -la  # Listar archivos en la raíz
      - ls -la backend  # Listar archivos dentro de backend para verificar

  - name: sonar_scan
    image: maven:3.6.3-jdk-11
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - cd backend/sistema-hoteles-be  # Navegar al directorio correcto
      - mvn clean verify sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN
