kind: pipeline
type: docker
name: sonar-scan-backend

steps:
  # SonarQube scan para backend-main
  - name: sonar-scan-backend-main
    image: sonarsource/sonar-scanner-cli
    user: root
    environment:
      SONAR_HOST_URL: "https://0zvgrx6x-9000.use.devtunnels.ms"
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=backend-main \
        -Dsonar.projectName='DRONEARQ-MAIN' \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.ws.timeout=600 \
        -Dsonar.java.binaries=target/classes

trigger:
  event:
    - push
    - pull_request
    - custom

secrets:
  - sonar_login