kind: pipeline
type: docker
name: backend-build

steps:
  - name: build-backend
    image: maven:3.8.6-eclipse-temurin-17
    environment:
      QUARKUS_PROFILE: prod
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install

  - name: sonar-scan-backend
    image: maven:3.8.6-eclipse-temurin-17  # Usamos la imagen de Maven para ejecutar el SonarQube
    environment:
      SONAR_HOST_URL: "https://0zvgrx6x-9000.use.devtunnels.ms"
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
        -Dsonar.projectKey=backend-main \
        -Dsonar.projectName='DRONEARQ-MAIN' \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.ws.timeout=600 \
        -Dsonar.java.binaries=target/classes
    depends_on:
      - build-backend

trigger:
  event:
    - push
    - pull_request
    - custom

secrets:
  - sonar_login