kind: pipeline
type: docker
name: sonar_analysis

steps:
  - name: sonar_scan
    image: maven:3.8.6-openjdk-17  # Usamos una imagen de Maven con JDK 17
    working_dir: /drone/src/Hotel/backend/sistema-hoteles-be  # Ruta absoluta dentro del contenedor
    commands:
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=DRONEARQ \
        -Dsonar.projectName='DRONEARQ' \
        -Dsonar.host.url=https://0zvgrx6x-9000.use.devtunnels.ms \
        -Dsonar.token=sqp_dd09130614766a06193ca48af6a7ac953caa1fc8
