kind: pipeline
type: docker
name: sonar_analysis

steps:
  - name: sonar_scan
    image: maven:3.6.3-jdk-11
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token  # El token de SonarQube
    commands:
      - cd backend/sistema-hoteles-be  # Navegar al directorio del backend
      - mvn clean verify sonar:sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN
