kind: pipeline
type: docker
name: backend-build

steps:
  # Build del backend con mvn install seguido de verify
  - name: build-backend
    image: maven:3.8.6-eclipse-temurin-17
    environment:
      QUARKUS_PROFILE: prod
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install   # Instala dependencias y genera artefactos
      - mvn verify          # Ejecuta tests y genera reportes como JaCoCo

  # SonarQube scan del backend incluyendo el reporte de cobertura
  - name: sonar-scan-backend
    image: sonarsource/sonar-scanner-cli
    user: root
    environment:
      SONAR_HOST_URL: "https://2036-181-209-150-83.ngrok-free.app"
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - sonar-scanner -X
        -Dsonar.projectKey=backend-main
        -Dsonar.sources=./
        -Dsonar.host.url=$SONAR_HOST_URL
        -Dsonar.login=$SONAR_TOKEN
        -Dsonar.ws.timeout=3600
        -Dsonar.java.binaries=target/classes
        -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
    depends_on:
      - build-backend

trigger:
  event:
    - push
    - pull_request
    - custom

secrets:
  - sonar_token