- name: sonar-scan-backend
  image: sonarsource/sonar-scanner-cli
  user: root
  environment:
    SONAR_HOST_URL: "https://0zvgrx6x-9000.use.devtunnels.ms"
    SONAR_TOKEN:
      from_secret: sonar_token
  commands:
    - cd Hotel/backend/sistema-hoteles-be
    - sonar-scanner -X
      -Dsonar.projectKey=backend-main
      -Dsonar.sources=./
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=$SONAR_TOKEN
      -Dsonar.ws.timeout=3000
      -Dsonar.java.binaries=target/classes
      -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
      -Dsonar.scm.exclusions.disabled=true  # Desactiva la exclusión basada en .gitignore
  depends_on:
    - build-backend
