kind: pipeline
type: docker
name: backend-build

steps:
  # Build del backend para el entorno main
  - name: build-backend-main
    image: maven:3.8.6-eclipse-temurin-17
    environment:
      QUARKUS_PROFILE: prod
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install

  # Unit tests para backend-main
  - name: test-backend-main
    image: maven:3.8.6-eclipse-temurin-17
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn test
    depends_on:
      - build-backend-main

  # SonarQube scan para backend-main
  - name: sonar-scan-backend-main
    image: sonarsource/sonar-scanner-cli
    user: root
    environment:
      SONAR_HOST_URL: "https://0zvgrx6x-9000.use.devtunnels.ms"
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=backend-main \
        -Dsonar.projectName='DRONEARQ-MAIN' \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.ws.timeout=600 \
        -Dsonar.java.binaries=target/classes
    depends_on:
      - test-backend-main

  # Push a Docker Hub para backend-main
  - name: publish-backend-main
    image: plugins/docker
    settings:
      repo: pmoralesm355/backend-main
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/backend/sistema-hoteles-be/Dockerfile
      context: Hotel/backend/sistema-hoteles-be
    depends_on:
      - sonar-scan-backend-main

  # Repetir los pasos anteriores para backend-dev
  - name: build-backend-dev
    image: maven:3.8.6-eclipse-temurin-17
    environment:
      QUARKUS_PROFILE: dev
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install

  - name: test-backend-dev
    image: maven:3.8.6-eclipse-temurin-17
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn test
    depends_on:
      - build-backend-dev

  - name: sonar-scan-backend-dev
    image: sonarsource/sonar-scanner-cli
    user: root
    environment:
      SONAR_HOST_URL: "https://0zvgrx6x-9000.use.devtunnels.ms"
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=backend-dev \
        -Dsonar.projectName='DRONEARQ-DEV' \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.ws.timeout=600 \
        -Dsonar.java.binaries=target/classes
    depends_on:
      - test-backend-dev

  - name: publish-backend-dev
    image: plugins/docker
    settings:
      repo: pmoralesm355/backend-dev
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/backend/sistema-hoteles-be/Dockerfile
      context: Hotel/backend/sistema-hoteles-be
    depends_on:
      - sonar-scan-backend-dev

  # Repetir los pasos anteriores para backend-uat
  - name: build-backend-uat
    image: maven:3.8.6-eclipse-temurin-17
    environment:
      QUARKUS_PROFILE: uat
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean install

  - name: test-backend-uat
    image: maven:3.8.6-eclipse-temurin-17
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn test
    depends_on:
      - build-backend-uat

  - name: sonar-scan-backend-uat
    image: sonarsource/sonar-scanner-cli
    user: root
    environment:
      SONAR_HOST_URL: "https://0zvgrx6x-9000.use.devtunnels.ms"
      SONAR_LOGIN:
        from_secret: sonar_login
    commands:
      - cd Hotel/backend/sistema-hoteles-be
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=backend-uat \
        -Dsonar.projectName='DRONEARQ-UAT' \
        -Dsonar.host.url=$SONAR_HOST_URL \
        -Dsonar.login=$SONAR_LOGIN \
        -Dsonar.ws.timeout=600 \
        -Dsonar.java.binaries=target/classes
    depends_on:
      - test-backend-uat

  - name: publish-backend-uat
    image: plugins/docker
    settings:
      repo: pmoralesm355/backend-uat
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: Hotel/backend/sistema-hoteles-be/Dockerfile
      context: Hotel/backend/sistema-hoteles-be
    depends_on:
      - sonar-scan-backend-uat

trigger:
  event:
    - push
    - pull_request
    - custom

secrets:
  - sonar_login
  - docker_username
  - docker_password