kind: pipeline
type: docker
name: build

steps:
  # Step 1: Unit Testing
  - name: unit_test
    image: maven:3.6.3-jdk-11
    commands:
      - cd backend/sistema-hoteles-be
      - mvn clean test

  # Step 2: SonarQube Analysis
  - name: sonar_scan
    image: maven:3.6.3-jdk-11
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - cd backend/sistema-hoteles-be
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=DRONEARQ \
        -Dsonar.projectName='DRONEARQ' \
        -Dsonar.host.url=https://0zvgrx6x-9000.use.devtunnels.ms \
        -Dsonar.login=$SONAR_TOKEN

  # Step 3: Docker Build and Push
  - name: build_docker
    image: plugins/docker
    settings:
      repo: pmoralesm355/sistema-hoteles-be
      tags: latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch:
        - dev
        - uat
        - main

  # Step 4: Deployment for Development
  - name: deploy_dev
    image: appleboy/ssh-action
    environment:
      SSH_PASSWORD:
        from_secret: ssh_password
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
    settings:
      host: $SSH_HOST
      username: $SSH_USER
      password: $SSH_PASSWORD
      script:
        - cd ~/Downloads/ProyectoARQ/ARQ/Hotel/
        - docker-compose down
        - docker-compose up -d
    when:
      branch:
        - dev

  # Step 5: Deployment for UAT
  - name: deploy_uat
    image: appleboy/ssh-action
    environment:
      SSH_PASSWORD:
        from_secret: ssh_password
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
    settings:
      host: $SSH_HOST
      username: $SSH_USER
      password: $SSH_PASSWORD
      script:
        - cd ~/Downloads/ProyectoARQ/ARQ/Hotel/
        - docker-compose down
        - docker-compose up -d
    when:
      branch:
        - uat

  # Step 6: Deployment for Production (Main Branch)
  - name: deploy_prod
    image: appleboy/ssh-action
    environment:
      SSH_PASSWORD:
        from_secret: ssh_password
      SSH_HOST:
        from_secret: ssh_host
      SSH_USER:
        from_secret: ssh_user
    settings:
      host: $SSH_HOST
      username: $SSH_USER
      password: $SSH_PASSWORD
      script:
        - cd ~/Downloads/ProyectoARQ/ARQ/Hotel/
        - docker-compose down
        - docker-compose up -d
    when:
      branch:
        - main
