kind: pipeline
type: docker
name: sonar_analysis

steps:
  # Step 1: SonarQube Analysis
  - name: sonar_scan
    image: maven:3.6.3-jdk-11
    environment:
      SONAR_TOKEN:
        from_secret: sonar_token
    commands:
      - cd backend/sistema-hoteles-be
      - mvn clean verify sonar:sonar \
        -Dsonar.projectKey=DRONEARQ \
        -Dsonar.projectName='DRONEARQ' \
        -Dsonar.host.url=https://0zvgrx6x-9000.use.devtunnels.ms \
        -Dsonar.login=$SONAR_TOKEN