node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    dir('Hotel/backend/sistema-hoteles-be') { 
      def mvn = tool 'Default Maven'
      withSonarQubeEnv('SonarQube') {
        sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=ARQ-PROJECT -Dsonar.projectName='ARQ PROJECT' -Dsonar.projectVersion=1.0 -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqa_a5a79f4a32d13a706b505f9dd073005433da41e6 -Dsonar.projectToken=sqp_2124e6b585886684de33068b3ab792a6a8a0512d"
      }
    }
  }
}
