node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    dir('Hotel/backend/sistema-hoteles-be') { 
      def mvn = tool 'Default Maven';
      withSonarQubeEnv('SonarQube') {
        sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=ARQ-PROJECT -Dsonar.projectName='ARQ PROJECT' -Dsonar.projectVersion=1.0 -Dsonar.login=sqa_a5a79f4a32d13a706b505f9dd073005433da41e6"
      }
    }
  }
}
