node {
  stage('SCM') {
    checkout scm
  }
  stage('SonarQube Analysis') {
    dir('Hotel/backend/sistema-hoteles-be') {
      def mvn = tool 'Default Maven';
      withSonarQubeEnv() {
        sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=ARQ-PROJECT -Dsonar.projectName='ARQ PROJECT'"
      }
    }
  }
}
