global:
  scrape_interval: 25s

scrape_configs:
  # Scrape cAdvisor metrics
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  # Scrape Drone metrics
  - job_name: 'drone'
    scrape_interval: 60s
    bearer_token: 532050eba76ed77d08b6afbee8e69ba8
    static_configs:
      - targets: ['0zvgrx6x-8082.use.devtunnels.ms']

  # Scrape Pushgateway metrics
  - job_name: 'pushgateway'
    scrape_interval: 15s
    static_configs:
      - targets: ['pushgateway:9091']  # Cambia 'pushgateway' por la dirección donde está corriendo
