name: Deploy to Environments

# Se ejecuta solo cuando un pull request es cerrado y mergeado
on:
  pull_request:
    types: 
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Solo si el PR fue mergeado
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull and deploy Docker images
      run: |
        docker-compose -f deploy.yml pull
        docker-compose -f deploy.yml up -d